// when hit webhook url through bluesnap then come data below mock
const CHARGE_THORUGH_BLUESNAP = {
  invoiceCountry: "US",
  invoiceZipCode: "30328",
  invoiceFirstName: "Shaul Cohen OR",
  invoiceFaxNumber: "",
  invoiceState: "AK",
  invoiceAddress2: "",
  invoiceEmail: "jhonedoe@gmail.com",
  invoiceLastName: "Yosef",
  invoiceAddress1: "760 MT VERNON HIGHWAY NE ,ATLANTA GA 30328",
  invoiceCompany: "",
  invoiceCity: "Atlanta",
  invoiceExtension: "52",
  invoiceMobilePhone: "",
  invoiceWorkPhone: "0523333333",
  invoiceTitle: "",
  lastName: "Yosef",
  country: "US",
  zipCode: "30328",
  extension: "52",
  personalId: "",
  address2: "",
  city: "Atlanta",
  address1: "760 MT VERNON HIGHWAY NE ,ATLANTA GA 30328",
  homePhone: "",
  brazilianId: "",
  title: "",
  accountId: "19601170",
  firstName: "Shaul Cohen OR",
  mobilePhone: "",
  faxNumber: "",
  company: "",
  workPhone: "0523584124",
  state: "AK",
  email: "jhonedue@gmail.com",
  username: "1482749022377",
  shippingCity: "Atlanta",
  shippingLastName: "Yosef",
  shippingCountry: "US",
  shippingZipCode: "30328",
  shippingMethod: "",
  shippingFirstName: "Shaul Cohen OR",
  shippingState: "AK",
  shippingAddress2: "",
  shippingAddress1: "760 MT VERNON HIGHWAY NE ,ATLANTA GA 30328",
  cardCategory: "",
  invoiceAmount: "9.00",
  language: "ENGLISH",
  creditCardType: "VISA",
  invoiceAmountUSD: "9.00",
  templateId: "2",
  productName: "testProduct",
  creditCardExpDate: "12/2017",
  contractOwner: "399928",
  referenceNumber: "38540558",
  contractName: "test123",
  currency: "USD",
  invoiceInfoURL:
    "https://shoppers.bluesnap.com/jsp/order_locator_info.jsp?refId=12FDA0621E5BCE8A&acd=1800702F9B89B236",
  remoteAddress: "0:0:0:0:0:0:0:1",
  contractChargePrice: "9.00",
  quantity: "1",
  productId: "310592",
  invoiceChargeCurrency: "USD",
  cardSubType: "CREDIT",
  invoiceChargeAmount: "9.00",
  referrer: "402970",
  contractPrice: "9.00",
  creditCardLastFourDigits: "1111",
  testMode: "N",
  contractId: "2199434",
  addCD: "N",
  untilDate: "12/26/2016 02:44 AM",
  paymentMethod: "CC",
  paymentType: "CC",
  invoiceLocalAmount: "9.00",
  invoiceURL:
    "https://dev6.bluesnap.com/jsp/show_invoice.jsp?ref=12FDA0621E5BCE8A",
  shopperOrderUrl:
    "https://shoppers.bluesnap.com/jsp/order_locator_info.jsp?refId=12FDA0621E5BCE8A&acd=1800702F9B89B236",
  originalRequestUrl: "http://localhost:8080/jsp/buynow.jsp?contractId=2199434",
  contractLocalPrice: "9.00",
  shopperAdminUrl:
    "https://shoppers.bluesnap.com/jsp/order_locator_info.jsp?refId=12FDA0621E5BCE8A&acd=1800702F9B89B236",
  invoiceLocalCurrency: "USD",
  recurringDisclaimer: "N",
  targetBalance: "BLUESNAP_ACCOUNT",
  promoteContractsNum: "0",
  EDWPeriod: "",
  EDWSurcharge: "",
  EDWAmountUSD: "",
  EDWContractId: "",
  EDWSurchargeUSD: "",
  EDWAmount: "",
  vatId: "",
  taxAmountUSD: "0.00",
  taxRate: "",
  taxChargeAmount: "0.00",
  authKey: "81277558eee27ca56ef9f1978b49f489",
  transactionType: "CHARGE",
  bluesnapNode: "1",
  plimusNode: "1",
  couponCode: "",
  licenseKey: "GIK-BEQB-URQP-CLYT",
  cvvSent: "Y",
  avsSent: "Y",
  cvvResponse: "Good match ",
  avsResponse: "All digits of address and ZIP match (5-digit ZIP) ",
  transactionDate: "12/26/2016 02:45 AM",
  merchantTransactionId: "",
  vendorId: "",
  vendorName: "",
  dpanLastFourDigits: "",
  dpanExpDate: "",
  sepaMandateId: "",
  sepaMandateDate: "",
  sepaIban: "",
  cardIssuingOrg: "JPMORGAN CHASE BANK, N.A.",
  binNumber: "411111",
  cardIssuingCountry: "us",
  "3DStatus": "3DS Not Enabled",
  binCategory: "CONSUMER",
  regulatedCard: "N",
  ipnV2: "Y",
};

const CANCELLATION_THORUGH_BLUESNAP = {
  lastName: "User",
  country: "",
  zipCode: "",
  extension: "",
  personalId: "",
  address2: "",
  city: "",
  address1: "",
  homePhone: "",
  brazilianId: "",
  title: "",
  accountId: "46519159",
  firstName: "Test ",
  mobilePhone: "",
  faxNumber: "",
  company: "",
  workPhone: "",
  state: "",
  email: "",
  username: "169157852481617241968131248710683",
  invoiceCountry: "",
  invoiceZipCode: "",
  invoiceFirstName: "Test ",
  invoiceFaxNumber: "",
  invoiceState: "",
  invoiceAddress2: "",
  invoiceEmail: "",
  invoiceLastName: "User",
  invoiceAddress1: "",
  invoiceCompany: "",
  invoiceCity: "",
  invoiceExtension: "",
  invoiceMobilePhone: "",
  invoiceWorkPhone: "",
  invoiceTitle: "",
  shippingCity: "",
  shippingLastName: "User",
  shippingCountry: "",
  shippingZipCode: "",
  shippingMethod: ["", ""],
  shippingFirstName: "Test ",
  shippingState: "",
  shippingAddress2: "",
  shippingAddress1: "",
  dpanLastFourDigits: "",
  cardCategory: "PLATINUM",
  invoiceAmount: "9.99",
  language: "ENGLISH",
  creditCardType: "DISCOVER",
  invoiceAmountUSD: "9.99",
  productName: "Diamond Plan",
  paymentType: "CC",
  creditCardExpDate: "2/2026",
  contractOwner: "1134229",
  referenceNumber: "1091544525",
  binCategory: "CONSUMER",
  contractName: "Diamond Plan",
  currency: "USD",
  cancelReason: "CANCELLED_BY_SELLER",
  invoiceInfoURL:
    "https://sandbox.bluesnap.com/jsp/order_locator_info.jsp?refId=A31C7C7ACB95BC41D3065130C3BFE691&acd=664B9EBCE76088CC",
  remoteAddress: "",
  quantity: "1",
  productId: "713209",
  invoiceChargeCurrency: "USD",
  cardSubType: "CREDIT",
  invoiceChargeAmount: "9.99",
  originalRefNum: "1091544525",
  regulatedCard: "Y",
  transactionType: "CANCELLATION",
  referrer: "",
  dpanExpDate: "",
  creditCardLastFourDigits: "1112",
  testMode: "N",
  contractId: "2913991",
  paymentMethod: "CC",
  subscriptionId: "48305749",
  addCD: "N",
  untilDate: "09/09/2023 03:55 AM",
  authKey: "",
  targetBalance: "BLUESNAP_ACCOUNT",
  taxAmountUSD: "0.00",
  taxRate: "",
  taxChargeAmount: "0.00",
  vatId: "",
  cancelledContractId: "2913991",
  overridePrice: "0.00",
  shopperOrderUrl:
    "https://sandbox.bluesnap.com/jsp/order_locator_info.jsp?refId=A31C7C7ACB95BC41D3065130C3BFE691&acd=664B9EBCE76088CC",
  templateId: "-99",
  licenseKey: "",
  promoteContractsNum: "0",
  bluesnapNode: "99",
  plimusNode: "99",
  couponCode: "",
  transactionDate: "08/16/2023 12:46 AM",
  merchantTransactionId: "",
  vendorId: "",
  vendorName: "",
  sepaMandateId: "",
  sepaIban: "",
  sepaMandateDate: "",
  ipnId: "3afd81c6-50a5-4770-bc02-bb838ed4e2bb",
};

const CONTRACT_CHANGE_THORUGH_BLUESNAP = {
  transactionType: "CONTRACT_CHANGE",
  lastName: "Patidar",
  country: "",
  zipCode: "",
  extension: "",
  personalId: "",
  address2: "",
  city: "",
  address1: "",
  homePhone: "",
  brazilianId: "",
  title: "",
  accountId: "46519025",
  firstName: "Manoj ",
  mobilePhone: "",
  faxNumber: "",
  company: "",
  workPhone: "",
  state: "",
  email: "",
  username: "169157768994517624179771543402162",
  invoiceCountry: "",
  invoiceZipCode: "",
  invoiceFirstName: "Manoj ",
  invoiceFaxNumber: "",
  invoiceState: "",
  invoiceAddress2: "",
  invoiceEmail: "",
  invoiceLastName: "Patidar",
  invoiceAddress1: "",
  invoiceCompany: "",
  invoiceCity: "",
  invoiceExtension: "",
  invoiceMobilePhone: "",
  invoiceWorkPhone: "",
  invoiceTitle: "",
  shippingCity: "",
  shippingLastName: "Patidar",
  shippingCountry: "",
  shippingZipCode: "",
  shippingMethod: "",
  shippingFirstName: "Manoj ",
  shippingState: "",
  shippingAddress2: "",
  shippingAddress1: "",
  contractChargePrice: "9.99",
  quantity: "1",
  productId: "713209",
  invoiceChargeCurrency: "USD",
  overridePrice: "0.00",
  invoiceAmount: "9.99",
  invoiceChargeAmount: "9.99",
  language: "ENGLISH",
  invoiceAmountUSD: "9.99",
  templateId: "0",
  productName: "Bronze Plan",
  referrer: "",
  contractOwner: "1134229",
  referenceNumber: "1091543391",
  contractPrice: "9.99",
  testMode: "N",
  contractId: "2913987",
  contractName: "Bronze Plan",
  currency: "USD",
  subscriptionId: "48305573",
  invoiceInfoURL:
    "https://sandbox.bluesnap.com/jsp/order_locator_info.jsp?refId=1B5EBD95219628691B0AB14E24254F33&acd=747C8385BF0D907A",
  remoteAddress: "",
  creditCardExpDate: "5/2026",
  dpanLastFourDigits: "",
  binCategory: "CONSUMER",
  dpanExpDate: "",
  creditCardLastFourDigits: "0126",
  cardSubType: "CHARGE CARD",
  cardCategory: "PERSONAL",
  creditCardType: "AMEX",
  regulatedCard: "N",
  addCD: "N",
  untilDate: "09/09/2023 03:41 AM",
  invoiceURL:
    "https://sandbox.bluesnap.com/jsp/show_invoice.jsp?ref=1B5EBD95219628691B0AB14E24254F33",
  originalInvoiceId: "1091543391",
  shopperOrderUrl:
    "https://sandbox.bluesnap.com/jsp/order_locator_info.jsp?refId=1B5EBD95219628691B0AB14E24254F33&acd=747C8385BF0D907A",
  resultCode: "SUCCESS",
  shopperAdminUrl:
    "https://sandbox.bluesnap.com/jsp/order_locator_info.jsp?refId=1B5EBD95219628691B0AB14E24254F33&acd=747C8385BF0D907A",
  targetBalance: "BLUESNAP_ACCOUNT",
  taxAmountUSD: "0.00",
  taxRate: "",
  taxChargeAmount: "0.00",
  vatId: "",
  oldContractName: "Subscription Bronze Plan",
  oldProductId: "713209",
  newContractId: "2918477",
  oldProductName: "Subscription",
  newProductId: "713209",
  newProductName: "Subscription",
  oldContractId: "2913987",
  originalRefNum: "1091543391",
  newContractName: "Subscription Bronze Plan",
  paymentType: "CC",
  paymentMethod: "CC",
  bluesnapNode: "99",
  plimusNode: "99",
  couponCode: "",
  authKey: "",
  licenseKey: "",
  transactionDate: "08/16/2023 01:29 AM",
  merchantTransactionId: "",
  vendorId: "",
  vendorName: "",
  cardIssuingOrg: "AMERICAN EXPRESS UK CONSUMER CHARGE",
  binNumber: "374245",
  cardIssuingCountry: "gb",
  ipnId: "d29ffc87-45b9-4234-b8e1-890ca144f1ce",
};
